overwrite: true
schema: graphql/schema.graphql
extensions:
  endpoints:
    localApi:
      url: "http://localhost:8080/graphql"
      headers:
        user-agent: "WebStorm"
documents:
  - "graphql/queries/**/*.graphql"
  - "graphql/mutations/**/*.graphql"
  - "graphql/fragments/**/*.graphql"
  - "actions/**/*.graphql"
generates:
  graphql/types.generated.ts:
    plugins:
      - "typescript"
      - add:
          content: 'import {Int64, Decimal, GormID, ObjectID, Token, Time} from "./scalars";'
  graphql/graphql.generated.ts:
    preset: "import-types-preset"
    presetConfig:
      typesPath: "@/graphql/types.generated"
    plugins:
      - "typescript-operations"
      - "typed-document-node"
      - add:
          content: 'import {Int64, Decimal, GormID, ObjectID, Token, Time} from "./scalars";'
    config:
      scalars:
        Int64: Int64
        Decimal: Decimal
        GormID: GormID
        ObjectID: ObjectID
        Token: Token
        Time: Time