overwrite: true
schema: graphql/schema.graphql
extensions:
  endpoints:
    localApi:
      url: "http://localhost:8080/graphql"
      headers:
        user-agent: "WebStorm"
documents:
  - "graphql/operations/**/*.graphql"
  - "graphql/fragments/**/*.graphql"
  - "actions/**/*.graphql"
generates:
  graphql/types.generated.ts:
    plugins:
      - "typescript"
      - add:
          content: 'import { Time, Upload } from "./scalars";'
  graphql/graphql.generated.ts:
    preset: "import-types-preset"
    presetConfig:
      typesPath: "@/graphql/types.generated"
    plugins:
      - "typescript-operations"
      - "typed-document-node"
      - add:
          content: 'import { Time, Upload } from "./scalars";'
    config:
      documentMode: "documentNode"
      importDocumentNodeExternallyFrom: "@apollo/client"
      scalars:
        Time: Time
        Upload: Upload